global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend-ml-staging"
    metrics_path: "/metrics"
    scheme: https
    static_configs:
      - targets: ["dvf-backend-staging.onrender.com"]
