services:
  backend-ml:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    ports:
      - "5173:80"
    depends_on:
      - backend-ml

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/grafana-local/prometheus-local.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend-ml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana-local:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
