services:
  backend-ml:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  service-history:
    build:
      context: ./service-history
    ports:
      - "4100:4100"
    env_file:
      - .env

  backend-main:
    build:
      context: ./backend-main
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      ML_SERVICE_URL: http://backend-ml:8000
      HISTORY_SERVICE_URL: http://service-history:4100
    depends_on:
      - backend-ml
      - service-history

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:4000}
    ports:
      - "5173:80"
    depends_on:
      - backend-main

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/grafana-local/prometheus-local.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend-ml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana-local:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
